# Generated by Django 3.0.8 on 2020-08-22 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex', '0025_auto_20200809_1536'),
        ('dcodex_collation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AlignedTranscription',
            new_name='Row',
        ),
    ]
