# Generated by Django 3.0.8 on 2020-08-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_collation', '0005_auto_20200825_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atext',
            name='token_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transition',
            name='end_token_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transition',
            name='start_token_id',
            field=models.IntegerField(),
        ),
    ]
