# Generated by Django 3.0.8 on 2020-08-25 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_collation', '0009_token_rank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='text',
            new_name='regularized',
        ),
    ]
