# Generated by Django 3.0.8 on 2020-08-25 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_collation', '0010_auto_20200826_0856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='regularized',
            new_name='text',
        ),
    ]
