# Generated by Django 3.0.8 on 2020-08-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_collation', '0011_auto_20200826_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='text',
            field=models.CharField(blank=True, help_text='A regularized form for the text of this state.', max_length=255, null=True),
        ),
    ]
