# Generated by Django 3.0.8 on 2020-08-26 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_collation', '0013_auto_20200826_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atext',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcodex_collation.State'),
        ),
        migrations.DeleteModel(
            name='Transition',
        ),
    ]
