# Generated by Django 3.0.8 on 2020-08-30 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_collation', '0017_auto_20200829_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RateSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('default_rate', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='dcodex_collation.Rate')),
            ],
        ),
        migrations.CreateModel(
            name='TransitionRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inverse', models.BooleanField(blank=True, default=None, help_text='If None, then the rate applies in both directions.', null=True)),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcodex_collation.Rate')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcodex_collation.RateSystem')),
                ('transition_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcodex_collation.TransitionType')),
            ],
        ),
    ]
