# Generated by Django 3.0.8 on 2020-08-22 05:57

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcodex', '0025_auto_20200809_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_to_id', jsonfield.fields.JSONField(help_text='Vocab dictionary')),
                ('id_to_word', models.BinaryField(help_text='Index of vocab dictionary')),
                ('matrix_data', models.BinaryField(help_text='Numpy array for the similarity matrix')),
                ('family', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='dcodex.Family')),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcodex.Verse')),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='The rank of this column in the alignment')),
                ('alignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcodex_collation.Alignment')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AlignedTranscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens', models.BinaryField(help_text='Numpy array for the tokens. IDs correspond to the vocab in the alignment')),
                ('alignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcodex_collation.Alignment')),
                ('transcription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcodex.VerseTranscription')),
            ],
        ),
    ]
