# Generated by Django 3.0.8 on 2020-08-23 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_collation', '0002_auto_20200822_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alignment',
            name='matrix_data',
        ),
    ]
