# Generated by Django 3.0.8 on 2020-08-25 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_collation', '0003_remove_alignment_matrix_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('inverse_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_token_id', models.PositiveIntegerField()),
                ('end_token_id', models.PositiveIntegerField()),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcodex_collation.Column')),
            ],
        ),
        migrations.CreateModel(
            name='AText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.PositiveIntegerField()),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcodex_collation.Column')),
            ],
        ),
    ]
