# Generated by Django 3.1.3 on 2021-03-09 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_collation', '0004_auto_20210221_0238'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitionTypeToIgnore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transition_type', models.ForeignKey(help_text='The transition type to treat as non-significant for analysis.', on_delete=django.db.models.deletion.CASCADE, to='dcodex_collation.transitiontype')),
            ],
        ),
    ]
