# Generated by Django 3.1.3 on 2021-04-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dcodex_collation", "0006_auto_20210309_0316"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="rank",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
