# Generated by Django 3.0.8 on 2020-08-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_collation', '0006_auto_20200825_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atext',
            name='token_id',
        ),
        migrations.RemoveField(
            model_name='transition',
            name='end_token_id',
        ),
        migrations.RemoveField(
            model_name='transition',
            name='start_token_id',
        ),
        migrations.AddField(
            model_name='atext',
            name='state',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transition',
            name='end_state',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transition',
            name='start_state',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
