# Generated by Django 3.0.8 on 2020-08-25 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_collation', '0007_auto_20200825_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='The characters of this token/word as they appear in the manuscript text.', max_length=255)),
                ('regularized', models.CharField(help_text='A regularized form of the text of this token.', max_length=255)),
                ('alignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcodex_collation.Alignment')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='A regularized form for the text of this state.', max_length=255)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcodex_collation.Column')),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcodex_collation.Column')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcodex_collation.Row')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dcodex_collation.State')),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dcodex_collation.Token')),
            ],
        ),
    ]
