# Generated by Django 3.0.8 on 2020-08-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_collation', '0008_cell_state_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='rank',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
