# Generated by Django 3.1.3 on 2021-06-13 01:27

from django.db import migrations

def migrate_data_forward(apps, schema_editor):
    from dcodex_collation.models import TransitionType
    for instance in TransitionType.objects.all():
        instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_collation', '0009_auto_20210612_1823'),
    ]

    operations = [
        migrations.RunPython(
            migrate_data_forward,
        ),
    ]
