# Generated by Django 3.0.8 on 2020-08-29 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_collation', '0016_remove_state_column'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cell',
            options={'ordering': ['column', 'row']},
        ),
        migrations.AddField(
            model_name='column',
            name='atext',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='dcodex_collation.State'),
        ),
        migrations.AddField(
            model_name='column',
            name='atext_notes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name='AText',
        ),
    ]
