# Generated by Django 3.0.9 on 2020-11-02 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_collation', '0018_rate_ratesystem_transitionrate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alignment',
            options={'ordering': ['family', 'verse']},
        ),
    ]
