# Generated by Django 3.0.9 on 2020-11-16 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_collation', '0019_auto_20201102_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alignment',
            name='id_to_word',
        ),
        migrations.RemoveField(
            model_name='alignment',
            name='word_to_id',
        ),
    ]
