# Generated by Django 3.0.11 on 2020-11-16 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcodex_collation', '0020_auto_20201116_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='row',
            name='tokens',
        ),
    ]
